id = "nord"
name = "Nord themes"
version = "0.0.9"
schema_version = 1
authors = ["Sergei Metlenkin <s.metlenkin@gmail.com>"]
description = "Nord themes"
repository = "https://github.com/mikasius/zed-nord-theme"
